### ISSUE TITLE
Gestures? Crown?

### ISSUE THREAD

**Issue by funky-monkey** [ezefranca/WatchNote#1]
Have you tried using other gestures for moving forward or back? Like Swiping the full screen instead of the buttons? Or turning the crown up/down to move between slides?
Not sure if the raise to wake has an API also but that would make for a nice interaction.

Anyways, my two cents :)

Best, 
Sidney

**Comment by ezefranca** [comment]
@funky-monkey Thanks for your comment! 
I Think this is great ideas, and in my spare time I will try to implement this :)

**Comment by eliottha** [comment]
@funky-monkey Added digital crown support in #2. Gestures can't be done easy. Will need to look deeper in it. Also added Shake support.

**Comment by ezefranca** [comment]
@funky-monkey thanks for the issue and @Eliottiosdevs thanks for implementing. Issue closed

**Comment by eliottha** [comment]
You welcome @ezefranca 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
